/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/molecules/AddTodo.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    EditTodoDialog: typeof import('./src/components/molecules/EditTodoDialog.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NoTodo: typeof import('./src/components/molecules/NoTodo.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectFlag: typeof import('./src/components/atoms/SelectFlag.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
